version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    expose:
      - 5432 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - fullstack
  web:
    build: .
    env_file:
      - .env
    environment:
      - DB_USERNAME:${DB_USERNAME}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_DATABASE_NAME:${DB_DATABASE_NAME} 
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go cmd/routes.go -b 0.0.0.0
    networks:
      - fullstack
    depends_on:
      - postgres


networks:
  fullstack:
    driver: bridge
